--DROP TABLE TEAMS
--DROP TABLE MATCHES

CREATE TABLE TEAMS
(
TEAM_ID INT IDENTITY(10,10) PRIMARY KEY,
TEAM_NAME VARCHAR(10)
)

CREATE TABLE MATCHES
(
MATCH_ID INT IDENTITY(1,1) PRIMARY KEY,
HOST_TEAM INT
,GUEST_TEAM INT
,HOST_GOALS INT
,GUEST_GOALS INT
)

INSERT INTO TEAMS VALUES 
 ('Give')
,('Never')
,('You')
,('Up')
,('Gonna')

INSERT INTO MATCHES VALUES
 ('30','20','1','0')
,('10','20','1','2')
,('20','50','2','2')
,('10','30','1','0')
,('30','50','0','1')